import test from 'node:test';
import assert from 'node:assert/strict';
import { parseHOTM } from '../lib/parseHOTM.ts';
import { parseHOTF } from '../lib/parseHOTF.ts';
import { parseGarden } from '../lib/parseGarden.ts';
import { parseRift } from '../lib/parseRift.ts';
import { parseFishing } from '../lib/parseFishing.ts';
import { compareProfiles } from '../lib/profileComparison.ts';
import { createProgressionRoadmap } from '../lib/progressionRoadmap.ts';
import type { DeterministicRecommendation } from '../lib/recommendations/index.ts';
import { marketPriceFor, parseMarketPrices, petMarketKey } from '../lib/marketPrices.ts';
import { validateIgn } from '../lib/ignValidation.ts';
import type { CollectionEntry } from '../lib/parseCollections.ts';
import { calculateNetworth, parseSkyhelperNetworth } from '../lib/calculateNetworth.ts';
import { hashPlayerProfile } from '../lib/evaluation/index.ts';

test('parses the current shared skill_tree schema for HOTM and powder semantics', () => {
  const parsed=parseHOTM({skill_tree:{nodes:{mining:{mining_speed:35,toggle_mining_speed:true,core_of_the_mountain:3}},experience:{mining:302_040},selected_ability:{mining:'pickobulus'},selected_skill_tree_slot:{mining:1}},mining_core:{powder_mithril:1_058_610,powder_spent_mithril:1_042_544,powder_mithril_total:16_066,powder_gemstone:14_750,powder_spent_gemstone:14_584,powder_gemstone_total:166}});
  assert.equal(parsed.available,true);assert.equal(parsed.level,6);assert.equal(parsed.powder.mithril.available,16_066);assert.equal(parsed.powder.mithril.total,1_058_610);assert.equal(parsed.peakOfTheMountainLevel,3);assert.equal(parsed.pickaxeAbility,'pickobulus');
});

test('retains compatibility with the legacy mining_core HOTM schema',()=>{const parsed=parseHOTM({mining_core:{experience:60_000,nodes:{mining_speed:5,special_0:2},powder_mithril:100,powder_spent_mithril:50,powder_mithril_total:150,selected_pickaxe_ability:'mining_speed_boost'}});assert.equal(parsed.level,4);assert.equal(parsed.powder.mithril.available,100);assert.equal(parsed.powder.mithril.total,150);assert.equal(parsed.peakOfTheMountainLevel,2)});

test('parses HOTF XP, selected slot, perks, ability, and Forest Whispers',()=>{const parsed=parseHOTF({skill_tree:{nodes:{foraging:{sweep:23,foraging_fortune:14,axe_toss:1},foraging_2:{center_of_the_forest:2}},experience:{foraging:14_410},selected_ability:{foraging:'axe_toss'},tokens_spent:{forest:5},selected_skill_tree_slot:{foraging:1}},foraging_core:{forests_whispers:118_186,forests_whispers_spent:117_836}});assert.equal(parsed.level,3);assert.equal(parsed.sweep,23);assert.equal(parsed.centerOfTheForestLevel,2);assert.equal(parsed.totalForestWhispers,236_022);assert.equal(parsed.selectedAbility,'axe_toss');assert.equal(parsed.perks.find(perk=>perk.id==='sweep')?.costToNextLevel,15_625)});

test('parses current Garden paths and crop-specific cumulative milestones',()=>{const parsed=parseGarden({garden:{garden_experience:20_351,commission_data:{total_completed:231,unique_npcs_served:81},resources_collected:{'INK_SACK:3':220_640,POTATO_ITEM:757_872},crop_upgrade_levels:{WHEAT:2,MELON:5},unlocked_plots_ids:['beginner_1'],composter_data:{organic_matter:2,fuel_units:3,compost_items:4,upgrades:{speed:1}}}});const cocoa=parsed.cropMilestones.find(c=>c.crop==='INK_SACK:3');const potato=parsed.cropMilestones.find(c=>c.crop==='POTATO_ITEM');assert.equal(parsed.level,12);assert.equal(parsed.visitors.completed,231);assert.equal(parsed.visitors.unique,81);assert.equal(cocoa?.name,'Cocoa Beans');assert.equal(cocoa?.level,14);assert.equal(cocoa?.amountToNextLevel,44_850);assert.equal(potato?.name,'Potato');assert.equal(potato?.level,17);assert.equal(parsed.bonusFortune,35);assert.equal(parsed.farmingFortune,null);assert.deepEqual(parsed.contestMedals,{bronze:0,silver:0,gold:0});assert.equal(parsed.composter.compost,4)});

test('parses current Rift timecharms, Mountaintop, souls, eyes, currencies, and Slayer',()=>{const parsed=parseRift({rift:{gallery:{secured_trophies:[{type:'slime'},{type:'mountain'}]},enigma:{bought_cloak:true,found_souls:['one','two']},dead_cats:{unlocked_pet:true},wither_cage:{killed_eyes:['castle','mountaintop']},access:{consumed_prism:true},lifetime_purchased_boundaries:['black_lagoon','mountaintop']},currencies:{motes_purse:1607},player_stats:{rift:{visits:13,lifetime_motes_earned:14250,motes_orb_pickup:19}},slayer:{slayer_bosses:{vampire:{xp:240,boss_kills_tier_0:2,boss_kills_tier_2:3}}}});assert.equal(parsed.timecharmsFound,2);assert.equal(parsed.timecharmsTotal,8);assert.equal(parsed.timecharms.find(charm=>charm.id==='mountain')?.value,true);assert.deepEqual(parsed.enigmaSouls,{found:2,total:51});assert.deepEqual(parsed.eyes,{found:2,total:7});assert.equal(parsed.currencies.motes,1607);assert.equal(parsed.vampireSlayer.level,3);assert.equal(parsed.vampireSlayer.bossKills,5);assert.equal(parsed.riftTimeSeconds,null)});

test('Fishing collections are selected strictly by verified category',()=>{const base=(rawKey:string,name:string,category:CollectionEntry['category']):CollectionEntry=>({rawKey,name,category,amount:1,tier:1,maxTier:10,nextTierRequirement:2,remaining:1,progressPercent:50,nextReward:null});const parsed=parseFishing({},[],[base('RAW_FISH','Raw Fish','Fishing'),base('INK_SACK:3','Cocoa Beans','Farming'),base('INK_SACK:4','Lapis Lazuli','Mining')]);assert.deepEqual(parsed.collections.map(c=>c.name),['Raw Fish'])});

test('new progression parsers safely represent missing API data',()=>{assert.equal(parseHOTM(null).available,false);assert.equal(parseHOTF(null).available,false);assert.equal(parseGarden(null).available,false);assert.equal(parseRift(null).available,false);assert.doesNotThrow(()=>parseFishing(null))});

test('profile comparison expands category detail and treats fewer missing accessories as stronger',()=>{const compared=compareProfiles('Left',{skills:[{skill:'mining',level:40}],accessories:{magicalPower:500,missingAccessories:[{},{}]},hotm:{level:7,totalPowderSpent:1000},garden:{level:10,visitors:{completed:50},cropMilestones:[{level:5}]},progressionScore:{score:60}},'Right',{skills:[{skill:'mining',level:35}],accessories:{magicalPower:600,missingAccessories:[{}]},hotm:{level:6,totalPowderSpent:2000},garden:{level:8,visitors:{completed:40},cropMilestones:[{level:4}]},progressionScore:{score:55}});assert.ok(compared.areas.length>10);assert.equal(compared.areas.find(area=>area.name==='Mining')?.stronger,'left');assert.equal(compared.areas.find(area=>area.name==='Missing Accessories')?.stronger,'right');assert.equal(compared.areas.find(area=>area.name==='Powder Spent')?.stronger,'right');assert.equal(compared.summary.leftWins+compared.summary.rightWins+compared.summary.ties,compared.areas.length)});

test('roadmap provides main and activity-specific deterministic tracks',()=>{const recommendation=(id:string,category:DeterministicRecommendation['category'],priority:number):DeterministicRecommendation=>({id,category,priority,title:id,explanation:'reason',evidence:[],suggestedAction:'action',expectedBenefit:'benefit',estimatedEffort:'Medium',confidence:90,knowledgeReferences:[]});const roadmap=createProgressionRoadmap([recommendation('mine','hotm',90),recommendation('farm','garden',80),recommendation('combat','accessories',70)]);assert.equal(roadmap.current?.id,'mine');assert.equal(roadmap.tracks.find(track=>track.id==='mining')?.current?.id,'mine');assert.equal(roadmap.tracks.find(track=>track.id==='farming')?.current?.id,'farm');assert.equal(roadmap.tracks.find(track=>track.id==='combat')?.current?.id,'combat');assert.equal(roadmap.tracks.find(track=>track.id==='fishing')?.current,null)});

test('market pricing prefers Bazaar, uses robust auction medians, and preserves lowest BIN',()=>{const prices=parseMarketPrices({products:{ENCHANTED_DIAMOND:{quick_status:{sellPrice:123,buyPrice:100}}}},{lowestBin:{ENCHANTED_DIAMOND:999,ASPECT_OF_THE_END:360000,'INK_SACK-3':7,GLACITE_BOOTS:694048},recent:{GLACITE_BOOTS:{recent:20000},ASPECT_OF_THE_END:{recent:350000}}});assert.deepEqual(prices.ENCHANTED_DIAMOND,{unitPrice:123,source:'bazaar'});assert.deepEqual(marketPriceFor('ASPECT_OF_THE_END',prices),{unitPrice:350000,source:'auction-median',recentMedianPrice:350000,lowestBinPrice:360000});assert.deepEqual(marketPriceFor('GLACITE_BOOTS',prices),{unitPrice:20000,source:'auction-median',recentMedianPrice:20000,lowestBinPrice:694048});assert.deepEqual(marketPriceFor('INK_SACK:3',prices),{unitPrice:7,source:'auction-bin',lowestBinPrice:7});assert.deepEqual(marketPriceFor('SOULBOUND_ITEM',prices,12),{unitPrice:12,source:'npc'});assert.equal(marketPriceFor('UNKNOWN',prices),null);assert.equal(petMarketKey('blue_whale','LEGENDARY'),'BLUE_WHALE;4')});

test('IGN validation enforces Minecraft username length and characters',()=>{assert.equal(validateIgn('').valid,false);assert.equal(validateIgn('ab').valid,false);assert.equal(validateIgn('abc').valid,true);assert.equal(validateIgn('player_123').valid,true);assert.match(validateIgn('abcdefghijklmnopq').message??'',/Length exceeded/);assert.match(validateIgn('bad-name').message??'',/letters, numbers, and underscores/);assert.equal(validateIgn('  westkorean  ').normalized,'westkorean')});

test('net worth sums liquid coins, soulbound stacks, pets, held items, and skins once',()=>{const networth=calculateNetworth({purse:500,bank:1000,inventoryItems:[{section:'inventory',slot:0,skyblockId:'VALUED',name:'Valued',count:2,rarity:null,stars:0,reforge:null,dungeonLevel:null,lore:['§8Co-op Soulbound']},{section:'enderChest',slot:0,skyblockId:'UNKNOWN',name:'Unknown',count:1,rarity:null,stars:0,reforge:null,dungeonLevel:null,lore:[]}],itemMetadata:{VALUED:{marketPrice:100}},pets:[{type:'SHEEP',tier:'LEGENDARY',exp:0,heldItem:'PET_ITEM',candyUsed:0,tierColor:'',skinId:'PET_SKIN_SHEEP',active:false,displayName:'Sheep',level:1}],marketPrices:{'SHEEP;4':{unitPrice:1000,source:'auction-median'},PET_ITEM:{unitPrice:200,source:'auction-bin'},PET_SKIN_SHEEP:{unitPrice:300,source:'auction-bin'}}});assert.equal(networth.total,3200);assert.equal(networth.inventory,200);assert.equal(networth.soulboundItems,200);assert.equal(networth.pets,1500);assert.equal(networth.liquid,1500);assert.equal(networth.pricedInventorySlots,1);assert.equal(networth.pricedSoulboundSlots,1);assert.equal(networth.unpricedInventorySlots,1);assert.equal(networth.pricedPets,1);assert.equal(networth.unpricedPets,0)});

test('adapts complete SkyHelper net worth without double-counting soulbound value',()=>{const parsed=parseSkyhelperNetworth({networth:2550,purse:100,bank:200,personalBank:50,types:{inventory:{total:1000,unsoulboundTotal:600,items:[{},{}]},pets:{total:1200,unsoulboundTotal:1200,items:[{}]}}});assert.ok(parsed);assert.equal(parsed.total,2550);assert.equal(parsed.liquid,350);assert.equal(parsed.inventory,1000);assert.equal(parsed.pets,1200);assert.equal(parsed.soulboundItems,400);assert.equal(parsed.source,'skyhelper')});

test('profile evaluation hashes are stable across object key order and change with profile data',()=>{assert.equal(hashPlayerProfile({b:2,a:1}),hashPlayerProfile({a:1,b:2}));assert.notEqual(hashPlayerProfile({a:1}),hashPlayerProfile({a:2}))});
