import PixelLock from './PixelLock';
import type { GardenProgress } from '@/lib/parseGarden';

const name = (value:string) => value.replace(/_/g,' ').replace(/\b\w/g,char=>char.toUpperCase());
export default function GardenCard({ progress }: { progress:GardenProgress }) {
  if (!progress.available) return <section className="mb-8 rounded-xl border border-neutral-800 bg-neutral-900 p-5"><h2 className="mb-3 text-xl font-semibold">The Garden</h2><div className="flex items-center gap-3 text-sm text-neutral-400"><PixelLock reason="Garden data is unavailable or API access is disabled."/>Garden data unavailable.</div></section>;
  return <section className="mb-8 rounded-xl border border-neutral-800 bg-neutral-900 p-5">
    <div className="mb-2 flex justify-between"><div><h2 className="text-xl font-semibold">The Garden</h2><p className="text-xs text-neutral-500">{progress.currentXp.toLocaleString()} XP · {progress.plotUnlocks.length} plots unlocked</p></div><span className="text-lime-300">Level {progress.level}</span></div>
    <div className="mb-5 h-3 overflow-hidden rounded-full bg-neutral-800"><div className="h-full bg-lime-500" style={{width:`${progress.progressPercent}%`}}/></div>
    <div className="mb-5 grid grid-cols-2 gap-2 text-sm sm:grid-cols-4"><div>Offers accepted<b className="block">{progress.visitors.completed.toLocaleString()}</b></div><div>Unique visitors<b className="block">{progress.visitors.unique}</b></div><div>Farming Fortune<b className="block">{progress.farmingFortune === null ? 'Not exposed by API' : progress.farmingFortune.toLocaleString()}</b></div><div>Crop upgrade Fortune<b className="block">{progress.bonusFortune.toLocaleString()}</b></div></div>
    <div className="mb-5"><div className="mb-1 flex justify-between text-xs text-neutral-400"><span>Offers milestone {progress.visitors.milestone}</span><span>{progress.visitors.progressPercent}%</span></div><div className="h-2 overflow-hidden rounded-full bg-neutral-800"><div className="h-full bg-emerald-500" style={{width:`${progress.visitors.progressPercent}%`}}/></div></div>
    <h3 className="mb-2 font-semibold">Crop milestones</h3><div className="mb-5 max-h-72 overflow-auto rounded-lg border border-neutral-800"><table className="w-full text-left text-sm"><thead className="sticky top-0 bg-neutral-950 text-xs text-neutral-500"><tr><th className="p-2">Crop</th><th>Milestone</th><th>Collected</th><th>Progress</th></tr></thead><tbody>{progress.cropMilestones.map(crop=><tr key={crop.crop} className="border-t border-neutral-800"><td className="p-2">{crop.name}</td><td>{crop.level}</td><td>{crop.amount.toLocaleString()}</td><td>{crop.progressPercent}%</td></tr>)}</tbody></table></div>
    <div className="grid gap-3 md:grid-cols-2"><div className="rounded-lg border border-neutral-800 bg-neutral-950 p-3"><h3 className="mb-2 text-sm font-semibold">Contest medals</h3><p className="text-xs text-neutral-400">{Object.entries(progress.contestMedals).map(([key,value])=>`${name(key)} ${value}`).join(' · ')}</p></div><div className="rounded-lg border border-neutral-800 bg-neutral-950 p-3"><h3 className="mb-2 text-sm font-semibold">Composter</h3><p className="text-xs text-neutral-400">Organic matter {progress.composter.organicMatter.toLocaleString()} · Fuel {progress.composter.fuel.toLocaleString()} · Compost {progress.composter.compost.toLocaleString()}</p></div></div>
  </section>;
}
