import type { DerivedProfileSnapshot } from './userProgressDatabase.ts';

export interface ProfileSnapshot<T=unknown>{id:string;profileKey:string;timestamp:number;parsedProfile:T}export interface SnapshotDelta{skillXp:number;collection:number;hotmXp:number;hotfXp:number;magicalPower:number;pets:number}
const sum=(v:unknown,key:string)=>Array.isArray(v)?v.reduce((s,x)=>s+(typeof x?.[key]==='number'?x[key]:0),0):0;const rec=(v:unknown):Record<string,unknown>=>v!==null&&typeof v==='object'?v as Record<string,unknown>:{};
export function diffSnapshots(current:unknown,previous:unknown):SnapshotDelta{const a=rec(current),b=rec(previous);const ah=rec(a.hotm),bh=rec(b.hotm),af=rec(a.hotf),bf=rec(b.hotf),aa=rec(a.accessories),ba=rec(b.accessories);return{skillXp:sum(a.skills,'currentXp')-sum(b.skills,'currentXp'),collection:sum(a.collections,'amount')-sum(b.collections,'amount'),hotmXp:(Number(ah.currentXp)||0)-(Number(bh.currentXp)||0),hotfXp:(Number(af.currentXp)||0)-(Number(bf.currentXp)||0),magicalPower:(Number(aa.magicalPower)||0)-(Number(ba.magicalPower)||0),pets:(Array.isArray(a.pets)?a.pets.length:0)-(Array.isArray(b.pets)?b.pets.length:0)}}

export function createDerivedSnapshot(profileKey: string, parsedProfile: unknown): DerivedProfileSnapshot {
  const profile = rec(parsedProfile), overview = rec(profile.overview), networth = rec(overview.networth), hotm = rec(profile.hotm), hotf = rec(profile.hotf), garden = rec(profile.garden), catacombs = rec(profile.catacombs), accessories = rec(profile.accessories);
  return { id: crypto.randomUUID(), profileKey, ign: typeof overview.ign === 'string' ? overview.ign : 'Unknown', profileName: typeof overview.profileName === 'string' ? overview.profileName : 'Unknown', timestamp: Date.now(), source: 'derived-profile', metrics: { networth: Number(networth.total) || 0, skillAverage: Number(overview.skillAverage) || 0, skyblockLevel: Number(overview.skyblockLevel) || 0, magicalPower: Number(accessories.magicalPower ?? overview.magicalPower) || 0, catacombsLevel: Number(catacombs.level ?? overview.catacombsLevel) || 0, hotmLevel: Number(hotm.level) || 0, hotfLevel: Number(hotf.level) || 0, gardenLevel: Number(garden.level) || 0, totalSkillXp: sum(profile.skills, 'currentXp'), totalCollections: sum(profile.collections, 'amount') } };
}
